---
- name: build and deploy in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    key_name: my-key7
    aws_region: eu-central-1
    ami_id: ami-0d527b8c289b4af7f
    pem_path: /Users/mikhailrozov/.ssh/my-key.pem
    instance_type: t2.micro
    my_local_cidr_ip: 0.0.0.0/0
    ec2_instances:
      - name: machine1
      - name: machine2
  tasks:
  - name: Creating Security Group for WebServer on AWS
    ec2_group:
      name: WebSG
      description: Security Group for Web Server allowing port for http and ssh
      region: "{{aws_region}}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

  - name: Create an EC2 instance
    ec2_instance:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      instance_type: "{{instance_type}}"
      image_id: "{{ami_id}}"
      wait: yes
      network:
        assign_public_ip: true
      security_group: WebSG
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 35
          delete_on_termination: true
      exact_count: 2
      name: demo
      state: running
    register: ec2
    with_items: ec2_instances

  - name: Add hosts group temporary inventory group builder
    add_host:
      name: "{{ ec2.results[0]['instances'][0]['public_ip_address'] }}"
      groups: builder
    with_indexed_items: ec2_instances

  - name: Add hosts group temporary inventory group prod
    add_host:
      name: "{{ ec2.results[0]['instances'][1]['public_ip_address'] }}"
      groups: prod
    with_indexed_items: ec2_instances

  - name: Wait for SSH
    wait_for:
      host:  "{{ item.public_ip_address }}"
      port: 22
      delay: 10
      timeout: 320
      state: started
    with_items: "{{ ec2.results[0]['instances'] }}"

- hosts: builder
  gather_facts: true 
  become: yes
  vars: 
    ansible_ssh_private_key_file: /Users/mikhailrozov/.ssh/my-key.pem
    ansible_ssh_user: "ubuntu"
    aws_region: eu-central-1
    aws_access_key: AKIAYH3IOQEKLIS6MINJ
    aws_secret_key: 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
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: apt install pkg
      apt:
        pkg:
        - openjdk-8-jdk
        - git
        - maven
        - python3-pip
        update_cache: yes
        state: latest

    - name: Git checkout
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /srv/boxfuse
        version: master
        update: yes

    - name: build
      shell:
        cmd: mvn package
        chdir: /srv/boxfuse
        
    - name: pip depenc
      pip:
        name:
          - botocore
          - boto3
          
    - name: Simple PUT operation
      amazon.aws.aws_s3:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        bucket: mybacket29s.test5.com
        object: hello.war
        src:  /srv/boxfuse/target/hello-1.0.war
        mode: put

- hosts: prod
  gather_facts: true 
  become: yes
  vars: 
    ansible_ssh_private_key_file: /Users/mikhailrozov/.ssh/my-key.pem
    ansible_ssh_user: "ubuntu"
    aws_region: eu-central-1
    aws_access_key: AKIAYH3IOQEKLIS6MINJ
    aws_secret_key: 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
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install tomcat9
      apt:
        pkg:
        - python3-pip
        - tomcat9
        update_cache: yes
    - name: pip depenc
      pip:
        name:
          - botocore
          - boto3
    - name: Simple Get operation
      amazon.aws.aws_s3:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        bucket: mybacket29s.test5.com
        object: hello.war
        dest:  /var/lib/tomcat9/webapps/hello.war
        mode: get

    - name: tomcat is started
      service:
        name: tomcat9
        state: restarted