---
- name: build and deploy in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:

    key_name: my-key7
    aws_region: eu-central-1
    ami_id: ami-0d527b8c289b4af7f
    pem_path: /Users/mikhailrozov/.ssh/my-key.pem
    instance_type: t2.micro
    my_local_cidr_ip: 0.0.0.0/0
    ec2_instances:
      - name: machine1
        ssh_user: "ubuntu"
      - name: machine2
        ssh_user: "ubuntu"
  tasks:
  - name: Creating Security Group for WebServer on AWS
    ec2_group:
      name: WebSG
      description: Security Group for Web Server allowing port for http and ssh
      region: "{{aws_region}}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  - name: Create an EC2 instance
    ec2_instance:
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      instance_type: "{{instance_type}}"
      image_id: "{{ami_id}}"
      wait: yes
      network:
        assign_public_ip: true
      security_group: WebSG
      volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 35
          delete_on_termination: true
      exact_count: 2
      name: demo2

      state: running
    register: ec2
    with_items: ec2_instances

  - name: Add hosts group temporary inventory group with pem path
    add_host:
      name: "{{ ec2.results[0]['instances'][0]['public_ip_address'] }}"
      groups: dynamic_hosts
    with_indexed_items: ec2_instances

- hosts: dynamic_hosts
  gather_facts: false 
  vars: 
    ansible_ssh_private_key_file: /Users/mikhailrozov/.ssh/my-key.pem
    ansible_ssh_user: "ubuntu"
  tasks:
    - name: apt update
      apt:
        pkg:
        - unzip
        - default-jdk
        - git
        - maven
        update_cache: yes
    - name: Git checkout
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /srv/boxfuse
        version: master
        update: yes
    - name: build
      shell:
        cmd: mvn package
        chdir: /srv/boxfuse
      

