// 1. JF
// 2. build boxfuse
// 3. make docker
// 4. push to registry
// 5. pull in prod

pipeline{
    agent none
    options { timestamps () }
    environment{
        docker_hub_auth = credentials("52b0db96-d581-4c99-b9df-3a105f72df67")
    }
    parameters{
        string(name: 'tag', defaultValue: 'v1', description: '')
    }
    stages{
        stage('Build'){
            agent {
                dockerfile {
                    filename 'Dockerfile.ci'
                    dir 'jenkins'
                    args "-v /var/run/docker.sock:/var/run/docker.sock"
                }
            }
            steps{
                script{
                    dir("${env.WORKSPACE}/jenkins"){
                        checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'boxfuse']], userRemoteConfigs: [[url: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git']]])
                        dir('boxfuse'){
                            sh "mvn package"
                        }
                        docker.withRegistry("https://index.docker.io/v1/", docker_hub_auth){
                            def webapp = docker.build("webapp:${params.tag}", "-f ${env.WORKSPACE}/jenkins/Dockerfile.ci")
                            webapp.push(params.tag)
                        }
                        // sh "docker build -t webapp:${params.tag} -f ${env.WORKSPACE}/jenkins/Dockerfile.ci ."
                        // sh "echo ${docker_hub_auth}|docker login --username dlod76 --password-stdin"
                        // sh "docker tag webapp dlod76/webapp:${params.tag}"
                        // sh "docker push dlod76/webapp:${params.tag}"
                    }
                }
            }
        }
    }
}
