// 1. JF
// 2. build boxfuse
// 3. make docker
// 4. push to registry
// 5. pull in prod

pipeline{
    agent none
    options { timestamps () }
    parameters{
        string(name: 'tag', defaultValue: 'v1', description: '')
    }
    stages{
        stage('Build'){
            agent {
                dockerfile {
                    filename 'Dockerfile.ci'
                    dir 'jenkins'
                    args "-v /var/run/docker.sock:/var/run/docker.sock"
                }
            }
            steps{
                script{
                    dir("${env.WORKSPACE}/jenkins"){
                        checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'boxfuse']], userRemoteConfigs: [[url: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git']]])
                        dir('boxfuse'){
                            sh "mvn package && mv ./target/*.war ../hello.war"
                        }
                        docker.withRegistry("https://index.docker.io/v1/", "52b0db96-d581-4c99-b9df-3a105f72df67"){
                            def webapp = docker.build("dlod76/webapp:${params.tag}", "-f ${env.WORKSPACE}/jenkins/Dockerfile.ci .")
                            webapp.push()
                        }
                    }
                }
            }
        }
        stage('Deploy'){
            agent{
                label 'node1'
            }
            steps{
                script{
                    sh "docker run -rm -d -p 8080:8080 --name webapp dlod76/webapp:${params.tag}"
                }
            }
        }
    }
}
