// 1. JF
// 2. build boxfuse
// 3. make docker
// 4. push to registry
// 5. pull in prod

pipeline{
    agent none
    options { timestamps () }
    // enviroment{

    // }
    // tools{

    // }
    stages{
        stage('Build'){
            agent {
                dockerfile {
                    filename 'Dockerfile.ci'
                    dir 'jenkins'
                    args '-v /tmp:/tmp'
                }
            }
            steps{
                sh "pwd&&ls -al"
            }
        }
    }
}
