version: '3.7'
services:
  builder:
    build:
      context: ./
      dockerfile: Dockerfile.build
    volumes:
      - data:/opt
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        db_user: devops12
        db_passwd: secret12
        dp_port: 3306
        db_ip: db
        db_name: database
    ports:
      - "8080:8080"
    volumes:
      - data:/usr/local/tomcat/webapps
    depends_on:
      - builder
      - db
  db:
    image: "mysql:5.7-oracle"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devops12
      MYSQL_PASSWORD: secret12
      MYSQL_DATABASE: database
volumes:
  dbdata:
  data: