version: '3'
services:
  tomcat-service:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - data:/opt/tomcat/webapps/
    ports:
      - "8080:8080"
    depends_on:
      - "builder"
      - "mysql_db"

  mysql_db:
    image: "mysql:8.0-oracle"
    restart: always
    ports:
      - 33060:33060    
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN

  builder:
    build:
      context: ./
      dockerfile: Dockerfile.build
    volumes:
      - data:/opt

volumes:  
  data:
